import type { QrTemplate } from './types';

export const QR_TEMPLATES: QrTemplate[] = [
  {
    id: 'classic',
    label: 'Clásico',
    category: 'negocio',
    config: {
      dotColor: '#1a1612',
      backgroundColor: '#ffffff',
      dotType: 'square',
      cornerSquareType: 'square',
      cornerDotType: 'square',
      maskShapeId: 'none',
      libraryShape: 'square',
      stickerId: null,
      effect3d: false,
    },
  },
  {
    id: 'clear',
    label: 'Sin plantilla',
    category: 'negocio',
    config: {
      dotColor: '#16a34a',
      backgroundColor: 'transparent',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'none',
      libraryShape: 'square',
      stickerId: null,
      effect3d: false,
    },
  },
  {
    id: 'panpaya-leaf',
    label: 'Verde Pan',
    category: 'comida',
    config: {
      dotColor: '#16a34a',
      backgroundColor: 'transparent',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'leaf',
      libraryShape: 'square',
      stickerId: 'food',
      effect3d: false,
    },
  },
  {
    id: 'pan-bread',
    label: 'Pan fresco',
    category: 'comida',
    config: {
      dotColor: '#c45c26',
      backgroundColor: '#fff7ed',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'bread',
      libraryShape: 'square',
      stickerId: 'food',
      effect3d: true,
    },
  },
  {
    id: 'croissant-gold',
    label: 'Croissant',
    category: 'comida',
    config: {
      dotColor: '#d97706',
      backgroundColor: '#fffbeb',
      dotType: 'classy-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'croissant',
      stickerId: 'chef',
      effect3d: false,
    },
  },
  {
    id: 'coffee-break',
    label: 'Café',
    category: 'comida',
    config: {
      dotColor: '#78350f',
      backgroundColor: '#fef3c7',
      dotType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      maskShapeId: 'coffee',
      stickerId: 'coffee',
      effect3d: false,
    },
  },
  {
    id: 'cupcake-pink',
    label: 'Postre',
    category: 'comida',
    config: {
      dotColor: '#db2777',
      backgroundColor: '#fdf2f8',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'cupcake',
      stickerId: 'party',
      effect3d: true,
    },
  },
  {
    id: 'donut-shop',
    label: 'Dona',
    category: 'comida',
    config: {
      dotColor: '#e11d48',
      backgroundColor: '#fff1f2',
      dotType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      maskShapeId: 'donut',
      libraryShape: 'circle',
      stickerId: 'food',
      effect3d: false,
    },
  },
  {
    id: 'chef-menu',
    label: 'Menú chef',
    category: 'comida',
    config: {
      dotColor: '#1e293b',
      backgroundColor: '#f8fafc',
      dotType: 'classy',
      cornerSquareType: 'classy',
      cornerDotType: 'dot',
      maskShapeId: 'chef-hat',
      stickerId: 'chef',
      effect3d: false,
    },
  },
  {
    id: 'brand-circle',
    label: 'Marca naranja',
    category: 'marca',
    config: {
      dotColor: '#c45c26',
      backgroundColor: '#fdf0e8',
      dotType: 'classy-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'circle',
      libraryShape: 'circle',
      stickerId: 'scan',
      effect3d: true,
    },
  },
  {
    id: 'brand-rounded',
    label: 'Suave marca',
    category: 'marca',
    config: {
      dotColor: '#c45c26',
      backgroundColor: '#ffffff',
      dotType: 'extra-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'rounded-sq',
      stickerId: null,
      effect3d: false,
    },
  },
  {
    id: 'brand-hex',
    label: 'Hexa marca',
    category: 'marca',
    config: {
      dotColor: '#ea580c',
      backgroundColor: '#fff7ed',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'square',
      maskShapeId: 'hexagon',
      stickerId: 'star',
      effect3d: false,
    },
  },
  {
    id: 'ocean',
    label: 'Océano',
    category: 'marca',
    config: {
      dotColor: '#2563eb',
      backgroundColor: '#eff6ff',
      dotType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      maskShapeId: 'circle',
      libraryShape: 'circle',
      stickerId: null,
      effect3d: false,
    },
  },
  {
    id: 'royal',
    label: 'Real',
    category: 'negocio',
    config: {
      dotColor: '#7c3aed',
      backgroundColor: '#f5f3ff',
      dotType: 'classy',
      cornerSquareType: 'classy',
      cornerDotType: 'dot',
      maskShapeId: 'shield',
      stickerId: 'star',
      effect3d: true,
    },
  },
  {
    id: 'badge-pro',
    label: 'Insignia',
    category: 'negocio',
    config: {
      dotColor: '#ca8a04',
      backgroundColor: '#fefce8',
      dotType: 'classy-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'badge',
      stickerId: 'sale',
      effect3d: true,
    },
  },
  {
    id: 'night',
    label: 'Nocturno',
    category: 'marca',
    config: {
      dotColor: '#e2e8f0',
      backgroundColor: '#0f172a',
      dotType: 'extra-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'diamond',
      stickerId: null,
      effect3d: false,
    },
  },
  {
    id: 'scan-dark',
    label: 'Scan me',
    category: 'negocio',
    config: {
      dotColor: '#ffffff',
      backgroundColor: '#1e293b',
      dotType: 'square',
      cornerSquareType: 'square',
      cornerDotType: 'square',
      maskShapeId: 'rounded-sq',
      stickerId: 'scan',
      effect3d: false,
    },
  },
  {
    id: 'phone-app',
    label: 'App móvil',
    category: 'negocio',
    config: {
      dotColor: '#0f172a',
      backgroundColor: '#e2e8f0',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'phone',
      stickerId: 'scan',
      effect3d: false,
    },
  },
  {
    id: 'mail-link',
    label: 'Correo',
    category: 'negocio',
    config: {
      dotColor: '#1d4ed8',
      backgroundColor: '#dbeafe',
      dotType: 'square',
      cornerSquareType: 'square',
      cornerDotType: 'square',
      maskShapeId: 'envelope',
      stickerId: 'scan',
      effect3d: false,
    },
  },
  {
    id: 'ticket-event',
    label: 'Entrada',
    category: 'eventos',
    config: {
      dotColor: '#7c3aed',
      backgroundColor: '#ede9fe',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'ticket',
      stickerId: 'party',
      effect3d: false,
    },
  },
  {
    id: 'celebration',
    label: 'Celebración',
    category: 'eventos',
    config: {
      dotColor: '#d97706',
      backgroundColor: '#fffbeb',
      dotType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      maskShapeId: 'star',
      stickerId: 'party',
      effect3d: true,
    },
  },
  {
    id: 'gift-box',
    label: 'Regalo',
    category: 'eventos',
    config: {
      dotColor: '#dc2626',
      backgroundColor: '#fef2f2',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'gift',
      stickerId: 'gift',
      effect3d: true,
    },
  },
  {
    id: 'party-balloon',
    label: 'Fiesta',
    category: 'eventos',
    config: {
      dotColor: '#db2777',
      backgroundColor: '#fce7f3',
      dotType: 'classy-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'star-6',
      stickerId: 'party',
      effect3d: false,
    },
  },
  {
    id: 'idea-bulb',
    label: 'Idea',
    category: 'eventos',
    config: {
      dotColor: '#eab308',
      backgroundColor: '#fefce8',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'bulb',
      stickerId: 'star',
      effect3d: true,
    },
  },
  {
    id: 'rose-heart',
    label: 'Corazón',
    category: 'amor',
    config: {
      dotColor: '#db2777',
      backgroundColor: '#fdf2f8',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'heart',
      stickerId: 'heart',
      effect3d: false,
    },
  },
  {
    id: 'flower-love',
    label: 'Flores',
    category: 'amor',
    config: {
      dotColor: '#e11d48',
      backgroundColor: '#fff1f2',
      dotType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      maskShapeId: 'flower',
      stickerId: 'flower',
      effect3d: false,
    },
  },
  {
    id: 'clover-luck',
    label: 'Trébol',
    category: 'amor',
    config: {
      dotColor: '#059669',
      backgroundColor: '#ecfdf5',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'clover',
      stickerId: 'flower',
      effect3d: false,
    },
  },
  {
    id: 'thumb-up',
    label: 'Me gusta',
    category: 'amor',
    config: {
      dotColor: '#2563eb',
      backgroundColor: '#dbeafe',
      dotType: 'extra-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'thumb',
      stickerId: 'heart',
      effect3d: true,
    },
  },
  {
    id: 'delivery-bag',
    label: 'Delivery',
    category: 'logistica',
    config: {
      dotColor: '#059669',
      backgroundColor: '#ecfdf5',
      dotType: 'rounded',
      cornerSquareType: 'square',
      cornerDotType: 'square',
      maskShapeId: 'bag',
      stickerId: 'truck',
      effect3d: false,
    },
  },
  {
    id: 'truck-route',
    label: 'Ruta',
    category: 'logistica',
    config: {
      dotColor: '#0f766e',
      backgroundColor: '#ccfbf1',
      dotType: 'square',
      cornerSquareType: 'square',
      cornerDotType: 'square',
      maskShapeId: 'truck',
      stickerId: 'truck',
      effect3d: false,
    },
  },
  {
    id: 'pin-map',
    label: 'Ubicación',
    category: 'logistica',
    config: {
      dotColor: '#dc2626',
      backgroundColor: '#fee2e2',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'location',
      stickerId: 'scan',
      effect3d: true,
    },
  },
  {
    id: 'helmet-work',
    label: 'Obra',
    category: 'logistica',
    config: {
      dotColor: '#ca8a04',
      backgroundColor: '#fef9c3',
      dotType: 'square',
      cornerSquareType: 'square',
      cornerDotType: 'square',
      maskShapeId: 'helmet',
      stickerId: 'sale',
      effect3d: false,
    },
  },
  {
    id: 'cart-shop',
    label: 'Tienda',
    category: 'logistica',
    config: {
      dotColor: '#0369a1',
      backgroundColor: '#e0f2fe',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'cart',
      stickerId: 'sale',
      effect3d: false,
    },
  },
  {
    id: 'tag-offer',
    label: 'Oferta',
    category: 'negocio',
    config: {
      dotColor: '#be123c',
      backgroundColor: '#ffe4e6',
      dotType: 'classy',
      cornerSquareType: 'classy',
      cornerDotType: 'dot',
      maskShapeId: 'tag',
      stickerId: 'sale',
      effect3d: true,
    },
  },
  {
    id: 'tshirt-merch',
    label: 'Merch',
    category: 'negocio',
    config: {
      dotColor: '#334155',
      backgroundColor: '#f1f5f9',
      dotType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      maskShapeId: 'tshirt',
      stickerId: 'star',
      effect3d: false,
    },
  },
  {
    id: 'sun-day',
    label: 'Día soleado',
    category: 'eventos',
    config: {
      dotColor: '#ea580c',
      backgroundColor: '#ffedd5',
      dotType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      maskShapeId: 'sun',
      stickerId: 'star',
      effect3d: false,
    },
  },
  {
    id: 'drop-water',
    label: 'Gota',
    category: 'marca',
    config: {
      dotColor: '#0284c7',
      backgroundColor: '#e0f2fe',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'drop',
      stickerId: null,
      effect3d: false,
    },
  },
  {
    id: 'cloud-soft',
    label: 'Nube',
    category: 'marca',
    config: {
      dotColor: '#64748b',
      backgroundColor: '#f8fafc',
      dotType: 'extra-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'cloud',
      stickerId: null,
      effect3d: false,
    },
  },
  {
    id: 'tree-eco',
    label: 'Eco',
    category: 'marca',
    config: {
      dotColor: '#15803d',
      backgroundColor: '#dcfce7',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'tree',
      stickerId: 'flower',
      effect3d: false,
    },
  },
  {
    id: 'paw-pet',
    label: 'Mascota',
    category: 'amor',
    config: {
      dotColor: '#92400e',
      backgroundColor: '#fef3c7',
      dotType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      maskShapeId: 'paw',
      stickerId: 'heart',
      effect3d: false,
    },
  },
  {
    id: 'burger-fast',
    label: 'Burger',
    category: 'comida',
    config: {
      dotColor: '#b45309',
      backgroundColor: '#fef3c7',
      dotType: 'rounded',
      cornerSquareType: 'square',
      cornerDotType: 'square',
      maskShapeId: 'burger',
      stickerId: 'food',
      effect3d: false,
    },
  },
  {
    id: 'pizza-night',
    label: 'Pizza',
    category: 'comida',
    config: {
      dotColor: '#c2410c',
      backgroundColor: '#ffedd5',
      dotType: 'classy-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'pizza',
      stickerId: 'food',
      effect3d: true,
    },
  },
  {
    id: 'ice-summer',
    label: 'Helado',
    category: 'comida',
    config: {
      dotColor: '#db2777',
      backgroundColor: '#fce7f3',
      dotType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      maskShapeId: 'icecream',
      stickerId: 'party',
      effect3d: false,
    },
  },
];
