import type { QrTemplate } from './types';

export const QR_TEMPLATES: QrTemplate[] = [
  {
    id: 'classic',
    label: 'Clásico',
    preview: '⬛',
    config: {
      dotColor: '#1a1612',
      backgroundColor: '#ffffff',
      dotType: 'square',
      cornerSquareType: 'square',
      cornerDotType: 'square',
      maskShapeId: 'none',
      libraryShape: 'square',
      effect3d: false,
    },
  },
  {
    id: 'emerald',
    label: 'Verde Pan',
    preview: '🍃',
    config: {
      dotColor: '#16a34a',
      backgroundColor: 'transparent',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'leaf',
      libraryShape: 'square',
      effect3d: false,
    },
  },
  {
    id: 'brand',
    label: 'Marca naranja',
    preview: '🟠',
    config: {
      dotColor: '#c45c26',
      backgroundColor: '#fdf0e8',
      dotType: 'classy-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'circle',
      libraryShape: 'circle',
      effect3d: true,
    },
  },
  {
    id: 'ocean',
    label: 'Océano',
    preview: '🌊',
    config: {
      dotColor: '#2563eb',
      backgroundColor: '#eff6ff',
      dotType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      maskShapeId: 'circle',
      libraryShape: 'circle',
      effect3d: false,
    },
  },
  {
    id: 'royal',
    label: 'Real',
    preview: '👑',
    config: {
      dotColor: '#7c3aed',
      backgroundColor: '#f5f3ff',
      dotType: 'classy',
      cornerSquareType: 'classy',
      cornerDotType: 'dot',
      maskShapeId: 'shield',
      libraryShape: 'square',
      effect3d: true,
    },
  },
  {
    id: 'night',
    label: 'Nocturno',
    preview: '🌙',
    config: {
      dotColor: '#e2e8f0',
      backgroundColor: '#0f172a',
      dotType: 'extra-rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'diamond',
      libraryShape: 'square',
      effect3d: false,
    },
  },
  {
    id: 'rose',
    label: 'Rosa',
    preview: '🌹',
    config: {
      dotColor: '#db2777',
      backgroundColor: '#fdf2f8',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'heart',
      libraryShape: 'square',
      stickerId: 'heart',
      effect3d: false,
    },
  },
  {
    id: 'delivery',
    label: 'Entrega',
    preview: '🚚',
    config: {
      dotColor: '#059669',
      backgroundColor: '#ecfdf5',
      dotType: 'rounded',
      cornerSquareType: 'square',
      cornerDotType: 'square',
      maskShapeId: 'bag',
      libraryShape: 'square',
      stickerId: 'truck',
      effect3d: false,
    },
  },
  {
    id: 'celebration',
    label: 'Celebración',
    preview: '🎉',
    config: {
      dotColor: '#d97706',
      backgroundColor: '#fffbeb',
      dotType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      maskShapeId: 'star',
      libraryShape: 'square',
      stickerId: 'party',
      effect3d: true,
    },
  },
  {
    id: 'minimal',
    label: 'Minimal',
    preview: '◻️',
    config: {
      dotColor: '#334155',
      backgroundColor: 'transparent',
      dotType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      maskShapeId: 'hexagon',
      libraryShape: 'square',
      effect3d: false,
    },
  },
  {
    id: 'scan-dark',
    label: 'Scan me',
    preview: '📲',
    config: {
      dotColor: '#ffffff',
      backgroundColor: '#1e293b',
      dotType: 'square',
      cornerSquareType: 'square',
      cornerDotType: 'square',
      maskShapeId: 'none',
      libraryShape: 'square',
      stickerId: 'scan',
      effect3d: false,
    },
  },
  {
    id: 'idea',
    label: 'Idea',
    preview: '💡',
    config: {
      dotColor: '#eab308',
      backgroundColor: '#fefce8',
      dotType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      maskShapeId: 'bulb',
      libraryShape: 'circle',
      effect3d: true,
    },
  },
];
